services:
  - type: web
    name: let-learn-earn-teach
    runtime: node
    buildCommand: npm install && npx prisma db push && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20
