"use client";import {useEffect,useState} from "react";import Nav from "@/components/Nav";
const empty={title:"",className:"",medium:"Hindi",teacherName:"Aman",price:0,about:"",customPoints:[] as string[]};
export default function Admin(){const [ok,setOk]=useState(false),[pw,setPw]=useState(""),[tab,setTab]=useState("All Users"),[batches,setBatches]=useState<any[]>([]),[form,setForm]=useState<any>(empty),[msg,setMsg]=useState("");
const load=()=>fetch("/api/batches").then(r=>r.json()).then(setBatches);useEffect(()=>{load()},[]);
const login=async()=>{const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:pw})});if(r.ok)setOk(true);else location.href="/";};
const create=async()=>{const r=await fetch("/api/batches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setMsg(r.ok?"Batch created":"Error creating batch");if(r.ok){setForm(empty);load()}};
const access=async(id:string,grant:boolean)=>{const email=prompt("Enter user's Gmail address");if(!email)return;await fetch(`/api/batches/${id}/access`,{method:grant?"POST":"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});alert(grant?"Access granted":"Access revoked");};
if(!ok)return <><Nav/><main className="wrap" style={{maxWidth:500}}><h1>Admin Access</h1><div className="card"><input className="input" type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder="Admin Password"/><button className="btn primary" onClick={login}>Continue</button></div></main></>;
return <><Nav/><main className="wrap"><h1>LET Admin Dashboard</h1><div className="admin-panel"><aside className="card">{["All Users","Create Batch","Manage Batch","About Tutor","Chats"].map(x=><p key={x}><button className="btn" onClick={()=>setTab(x)}>{x}</button></p>)}</aside><section className="card">{tab==="All Users"&&<><h2>All Users & Batch Access</h2><p className="muted">Grant/revoke by entering the user's registered Gmail.</p>{batches.map(b=><div className="msg" key={b.id}><b>{b.title}</b><div className="row"><button className="btn primary" onClick={()=>access(b.id,true)}>Grant Access</button><button className="btn" onClick={()=>access(b.id,false)}>Revoke Access</button></div></div>)}</>}
{tab==="Create Batch"&&<><h2>Create Batch</h2>{["title","className","medium","teacherName","price","about"].map(k=>k==="about"?<textarea key={k} className="input" placeholder="About Batch" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>:<input key={k} className="input" placeholder={k} type={k==="price"?"number":"text"} value={form[k]} onChange={e=>setForm({...form,[k]:k==="price"?Number(e.target.value):e.target.value})}/>)}<input className="input" placeholder="Image URL (or upload using API)" onChange={e=>setForm({...form,imageUrl:e.target.value})}/><input className="input" placeholder="Custom points separated by |" onChange={e=>setForm({...form,customPoints:e.target.value.split("|").filter(Boolean)})}/><button className="btn primary" onClick={create}>Create Batch</button><p>{msg}</p></>}
{tab==="Manage Batch"&&<><h2>Manage Batch</h2><p className="muted">Create batch content through the protected content API. This source package includes section/item/notification endpoints for Classes, Notes and Practice.</p>{batches.map(b=><div className="msg" key={b.id}><b>{b.title}</b><p>POST /api/batches/{b.id}/content</p></div>)}</>}
{tab==="About Tutor"&&<><h2>About Tutor</h2><p>GET/PUT API: /api/tutor. Stores heading, subheading, text, image and links as JSON.</p></>}
{tab==="Chats"&&<><h2>Chats</h2><p className="muted">Conversation and message APIs are included for private student doubts and admin replies.</p></>}</section></div></main></>}
